### ISSUE TITLE
Solhint is not installed exception

### ISSUE THREAD

**Issue by PureIso** [protofire/solhint#14]
**Exception**
I am getting the following exception if anyone can help me out.
"Solhint is not installed: For correct run of Solidity Solhint Plugin you need to install Solhint."

**Installed**
I have the latest NodeJs installed.
I also have Solidity and Solhint (1.1.8) installed via Browse Repository

**OS**
Operating System: Windows 10 x64
IDE: IntelliJ

In addition, how do you get started once you have all package installed?  What is the run command?

**Comment by idrabenia** [comment]
Hi Ola,

You need to go to Settings > Plugins

And install plugin intellij-solidity. 

After that you need to restart idea. 

Thank you!

If you will any troubles please notify us!

Thanks!

**Comment by PureIso** [comment]
Hi, 
Thank you for the very fast reply.  Please find attached images below which further explains the issue.
![image0](https://user-images.githubusercontent.com/3818856/33543372-b2149054-d8ce-11e7-9a7a-7f83d31fc134.PNG)
I have Solidity and Solhint installed.

![image1](https://user-images.githubusercontent.com/3818856/33543314-73c9399e-d8ce-11e7-85af-12fc2eccc118.PNG)
Solhint error, in which IntelliJ is notifying me to fix.  The nodeJS path is correct (Version:8.9.1).

![image3](https://user-images.githubusercontent.com/3818856/33543525-3dc4b688-d8cf-11e7-8192-d298098e2367.PNG)
I also have nodeJS installed.

Kind Regards

**Comment by idrabenia** [comment]
Hi @PureIso,

On second image there are button "Install Solhint". Can you press it.

Does it works correct after that, or throw any errors?

Thanks!
\- Ilya

**Comment by PureIso** [comment]
@idrabenia I did multiple times, at first it shows installing, please see image attached below and then it revert back to the "Solhint  package not found for the specific nodejs installtion".

![image4](https://user-images.githubusercontent.com/3818856/33568474-76bddd8a-d91e-11e7-9ffc-7620c2b3e764.PNG)

In addition,  I tried multiple versions of nodejs and no luck.  I will trying it on ubuntu next.

**Comment by idrabenia** [comment]
@PureIso Sory for misunderstanding.

If not difficult - can you 
1. Open **Menu Help > Show Log in Explorer**. Copy log and attach here.
2. If not difficult can you execute manually **"C:\Program Files\nodejs\node.exe" "C:\Prog
ram Files\nodejs\node_modules\npm\bin\npm-cli.js" install -g solhint** and attach here results - if you have any errors

Thanks you!
\- Ilya

**Comment by PureIso** [comment]
(1)
**idea.log info:**
2017-12-05 11:04:08,065 [  53641]   WARN - a.solhint.client.SolhintClient - Can not connect to Solhint validation server 
java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at idrabenia.solhint.client.SolhintClient.verifyFile(SolhintClient.kt:35)
	at idrabenia.solhint.client.SolhintClient.fileErrors(SolhintClient.kt:29)
	at idrabenia.solhint.Inspections.runSolhint(Inspections.kt:26)
	at idrabenia.solhint.Inspections.checkFile(Inspections.kt:16)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:142)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**(2)**
The command runs fine (see below) but still get the same error.
![image5](https://user-images.githubusercontent.com/3818856/33604262-292ae3a8-d9ad-11e7-8b72-92fe587b9ff1.PNG)

**Comment by idrabenia** [comment]
If not difficult - can you execute 
where solhint
where npm
where node

In your command line. 

Thanks!
\- Ilya

**Comment by dukei** [comment]
I have the same issue. All plugins are installed, pressing Install Solhint does something and then revert to showing error about Solhint is not installed again.

Here is what you asked to execute:

C:\Program Files\nodejs\node_modules>where solhint
C:\Users\k\AppData\Roaming\npm\solhint
C:\Users\k\AppData\Roaming\npm\solhint.cmd

C:\Program Files\nodejs\node_modules>where npm
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd

C:\Program Files\nodejs\node_modules>where node
C:\Program Files\nodejs\node.exe

**Comment by dukei** [comment]
@idrabenia is there any progress on this?

**Comment by runnerFeng** [comment]
![_ i y3 082e 3unen o a](https://user-images.githubusercontent.com/19525953/34283285-dbaf1278-e705-11e7-8605-85136743c89b.png)
![go 0zb200 a_vha7i2u hn2](https://user-images.githubusercontent.com/19525953/34283286-dbde482c-e705-11e7-8e84-b9df927cd0ee.png)

**Comment by runnerFeng** [comment]
@dukei @PureIso I've solved this problem,you can try.
1.install node.js default
![a](https://user-images.githubusercontent.com/19525953/34291947-aaf025c6-e739-11e7-885f-48140ca116f6.png)
2.check this path
![2](https://user-images.githubusercontent.com/19525953/34292048-23dc953c-e73a-11e7-8f7f-59a491fc6ee3.png)
![3](https://user-images.githubusercontent.com/19525953/34292049-24102ffa-e73a-11e7-8eb2-d806f032d07f.png)
3.config node.js and install solhint 
![4](https://user-images.githubusercontent.com/19525953/34292139-82f12d4e-e73a-11e7-91fc-dd7dde6645ad.png)
4.open idea and install solhint
![5](https://user-images.githubusercontent.com/19525953/34292343-891aec40-e73b-11e7-9176-fe7c386495d7.png)
![6](https://user-images.githubusercontent.com/19525953/34292344-896053ac-e73b-11e7-935d-ddc2b7f9690b.png)
![7](https://user-images.githubusercontent.com/19525953/34292345-8994ef2c-e73b-11e7-9865-cb602ef9657f.png)

**Comment by PureIso** [comment]
@runnerFeng thank you.  I can confirm it work and issue resolved.

**Comment by dukei** [comment]
@runnerFeng Thank you, it helps.
@idrabenia So the problem might be that solhint plugin does not respect npm config prefix setting.

**Comment by idrabenia** [comment]
Hello guys,

Thank you for the feedback!

We are working on fix of this issue. 
The fix will be available during next two weeks!

Thanks!
\- Ilya

**Comment by Teslima02** [comment]
Hello guys please help me out.. The solution above is not working for me

After i perform runnerFeng step 3 solution -> "npm install -g solhint" 

This is the error it return for me->
Unhandled rejection Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\cache'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by dukei** [comment]
@Teslima02, you should run console under administrator for this command.

**Comment by Teslima02** [comment]
I found solution to it..... i uninstall the latest nodejs that i install and install version 7 and it works

**Comment by Teslima02** [comment]
Thanks @dukei

**Comment by runnerFeng** [comment]
@Teslima02 https://www.jianshu.com/p/03a76b2e7e00

**Comment by idrabenia** [comment]
Hi guys,

Thank you for your participation in project improvement!

There is new version of Solhint plugin. It contains fix of this issue.

https://plugins.jetbrains.com/plugin/10177-solidity-solhint 


Thanks!
\- Ilya

**Comment by dherykw** [comment]
Not working for me on Ubuntu with Node versions:

- v7.10
- v8.9
- v10.16
- v12.18

**log**: 2020-07-31 11:57:49,099 [1406472]   WARN - a.solhint.client.SolhintClient - Can not connect to Solhint validation server

**Comment by fvictorio** [comment]
Hi @dherykw, can you open a new issue with details about what's not working for you?

**Comment by dherykw** [comment]
sure

**Comment by adjisb** [comment]
Hi, I have the same issue on debian.
In the logs:
2021-09-10 16:31:29,569 [   6117]   WARN - a.solhint.client.SolhintClient - Can not connect to Solhint validation server 

node version: v14.17.6
I'm using nvm and solhint is installed in:  ~/.nvm/versions/node/v14.17.6/bin/solhint
When I point the javascript file to ~/.nvm/versions/node/v14.17.6/lib/node_modules/solhint/solhint.js it works for a second (solhint is ready to...) but then it doesn't do anything and if I open the window again it says that solhint is not found.

**Comment by adjisb** [comment]
Hi, I have the same issue on debian.
In the logs:
2021-09-10 16:31:29,569 [ 6117] WARN - a.solhint.client.SolhintClient - Can not connect to Solhint validation server

node version: v14.17.6
I'm using nvm and solhint is installed in: ~/.nvm/versions/node/v14.17.6/bin/solhint
When I point the javascript file to ~/.nvm/versions/node/v14.17.6/lib/node_modules/solhint/solhint.js it works for a second (solhint is ready to...) but then it doesn't do anything and if I open the window again it says that solhint is not found.
