### ISSUE TITLE
Solhint is not found

### ISSUE THREAD

**Issue by dherykw** [protofire/solhint#244]
**Error**
I am getting the following error in the Pycharm Event Log console:
 "Solhint is not found: Please provide correct path to Solhint. Fix"

**OS**
Ubuntu 20.04
IDE: Pycharm 202.6397.98

**Dependencies**
Node installed with nvm
version tested:
- v7.10.1
- v8.9.4
- v8.15.0
- v10.16.0
- v12.18.2

Solhint installed with npm:
```
$ npm install -g solhint
```

**Solidity sholhint settings**
![image](https://user-images.githubusercontent.com/3577018/89048400-11574d80-d350-11ea-9af7-6e5699ce1231.png)

I tried with .js file with same result
"/home/********/.nvm/versions/node/v7.10.1/lib/node_modules/solhint/solhint.js"

**idea.log**
WARN - a.solhint.client.SolhintClient - Can not connect to Solhint validation server 
java.net.ConnectException: Conexión rehusada (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)

Thank you

**Comment by fvictorio** [comment]
Hey @dherykw, this seems like a problem with https://github.com/protofire/idea-solidity-solhint, right? I think that issue belongs there (but I don't think anyone is maintaining it, to be honest). Please re-open if you think this is an issue with solhint itself!
