### ISSUE TITLE
Error message appears when running files through remote-atom

### ISSUE THREAD

**Issue by patrickclery** [protofire/solhint#29]
I'm getting an error message when editing files that are in certain directories:

```
[Linter] Error running Solhint
See console for more info

...(console)...

C:\Users\patri\.atom\packages\linter\lib\linter-registry.js:177 [Linter] Error running Solhint Error: Invalid or no `directory` provided
    at Object.validateFind (C:\Users\patri\.atom\packages\atom-solidity-linter\node_modules\atom-linter\lib\helpers.js:92:11)
    at Object.<anonymous> (C:\Users\patri\.atom\packages\atom-solidity-linter\node_modules\atom-linter\lib\index.js:67:13)
    at Generator.next (<anonymous>)
    at step (C:\Users\patri\.atom\packages\atom-solidity-linter\node_modules\atom-linter\lib\index.js:145:191)
    at C:\Users\patri\.atom\packages\atom-solidity-linter\node_modules\atom-linter\lib\index.js:145:437
    at Object.<anonymous> (C:\Users\patri\.atom\packages\atom-solidity-linter\node_modules\atom-linter\lib\index.js:145:99)
    at Object.findCachedAsync (C:\Users\patri\.atom\packages\atom-solidity-linter\node_modules\atom-linter\lib\index.js:86:18)
    at file:///C:/Users/patri/.atom/packages/atom-solidity-linter/lib/helpers.js:15:45
    at Generator.next (<anonymous>)
    at step (file:///C:/Users/patri/.atom/packages/atom-solidity-linter/lib/helpers.js:49:2)
```

For example, by default, remote-atom creates files in Windows 10 at AppData/Local/Temp. If I move the exact same file to these directories:

AppData/Local
AppData
OneDrive/Documents
(or my home dir)

it doesn't work. However, if I move it to $HOME/OneDrive/Documents/solidity I no longer get those error message. File permissions are exact same, moving the exact same file. I thought maybe it was remote-atom but it seems to happen regardless of whether remote-atom creates a file or I move one.

**Comment by mgarciap** [comment]
Hi @patrickclery , is this still happening?

**Comment by dbale-altoros** [comment]
Sorry for the late response. We will close this issue because it has more than 4 years
There are several new releases available and we will be updating solhint on regular basis with a dedicated team to it
Thanks for posting

Feel free to open any issue if you have any problem.
We will be addressing them
