### ISSUE TITLE
Error: Fallback functions cannot have parameters

### ISSUE THREAD

**Issue by leonardishere** [protofire/solhint#364]
These are both legal declarations of the fallback function. Hardhat/ethers successfully compiles and executes both
```solidity
fallback() external payable;
fallback(bytes calldata data) external payable returns (bytes memory result);
```

Using the first solhint has no issues. Using the second I get

```
$ solhint contracts/*
/usr/lib/node_modules/solhint/lib/index.js:40
      throw e
      ^

Error: Fallback functions cannot have parameters
    at ASTBuilder.FunctionDefinition (/usr/lib/node_modules/solhint/node_modules/@solidity-parser/parser/dist/index.cjs.js:25509:17)
    at ASTBuilder.visit (/usr/lib/node_modules/solhint/node_modules/@solidity-parser/parser/dist/index.cjs.js:26831:42)
    at ASTBuilder.ContractPart (/usr/lib/node_modules/solhint/node_modules/@solidity-parser/parser/dist/index.cjs.js:25458:17)
    at ASTBuilder.visit (/usr/lib/node_modules/solhint/node_modules/@solidity-parser/parser/dist/index.cjs.js:26831:42)
    at ASTBuilder.<anonymous> (/usr/lib/node_modules/solhint/node_modules/@solidity-parser/parser/dist/index.cjs.js:26816:26)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (/usr/lib/node_modules/solhint/node_modules/@solidity-parser/parser/dist/index.cjs.js:26815:20)
    at ASTBuilder.ContractDefinition (/usr/lib/node_modules/solhint/node_modules/@solidity-parser/parser/dist/index.cjs.js:25445:22)
    at ASTBuilder.visit (/usr/lib/node_modules/solhint/node_modules/@solidity-parser/parser/dist/index.cjs.js:26831:42)
    at ASTBuilder.<anonymous> (/usr/lib/node_modules/solhint/node_modules/@solidity-parser/parser/dist/index.cjs.js:26816:26)
```

I see some issues and PRs about changing the parser that might solve this issue. Using solidity 0.8.x and solhint 3.3.7 if that makes a difference

**Comment by dbale-altoros** [comment]
This issue is fixed when upgrading to the last solidity parser version (0.14.5)
